import React from 'react';
import { motion } from 'motion/react';
import { 
  BarChart3, 
  LineChart, 
  Terminal, 
  Database, 
  Table, 
  Cloud,
  CheckCircle,
  Award 
} from 'lucide-react';

export default function SkillsArsenal() {
  const tools = [
    { 
      name: 'Tableau', 
      icon: BarChart3,
      exp: '3+ Years Exp',
      desc: 'Created cohort retention dashboard saving ₹2.2Cr/mo.'
    },
    { 
      name: 'Power BI', 
      icon: LineChart,
      exp: '3+ Years Exp',
      desc: 'Formulated visual tracking of agricultural sales demand.'
    },
    { 
      name: 'Python', 
      icon: Terminal,
      exp: '2.5+ Years Exp',
      desc: 'Autogenerated lead scoring models and churn forecasting.'
    },
    { 
      name: 'SQL', 
      icon: Database,
      exp: '4+ Years Exp',
      desc: 'Designed complex analytical queries on Redshift & Postgres.'
    },
    { 
      name: 'Excel', 
      icon: Table,
      exp: '5+ Years Exp',
      desc: 'Advanced statistical forecasting and pivot-table segmentation.'
    },
    { 
      name: 'Snowflake', 
      icon: Cloud,
      exp: '2+ Years Exp',
      desc: 'Built pipelines of performance marketing campaign telemetry.'
    }
  ];

  const competencies = [
    { 
      name: 'Data Visualization', 
      value: 95,
      detail: 'Proficient in crafting interactive dashboards that summarize performance dynamics across various ad platforms.'
    },
    { 
      name: 'Performance Marketing', 
      value: 92,
      detail: 'Expertise in lower-funnel acquisition, budgeting strategies, and optimizing customer acquisition cost (CAC).'
    },
    { 
      name: 'User Behavior Analysis', 
      value: 90,
      detail: 'Specialized in predicting early-stage churn, building cohort analysis frameworks, and cohort decay optimization.'
    }
  ];

  const certifications = [
    { title: 'Google Digital Marketing', subtitle: 'Certified Professional' },
    { title: 'Python Developer', subtitle: 'Udemy Specialization' }
  ];

  return (
    <div>
      {/* Tools Grid */}
      <div className="grid grid-cols-2 md:grid-cols-6 gap-6">
        {tools.map((tool, idx) => {
          const Icon = tool.icon;
          return (
            <div 
              key={idx} 
              className="relative group/tooltip liquid-glass p-8 flex flex-col items-center justify-center gap-4 hover:border-primary/50 hover:scale-[1.03] hover:bg-surface/75 transition-all duration-300 rounded-3xl cursor-help"
            >
              <Icon className="w-10 h-10 text-on-surface-variant group-hover/tooltip:text-primary group-hover/tooltip:scale-110 transition-all duration-350" />
              <span className="font-mono text-xs font-bold leading-none tracking-wide text-center text-on-surface">
                {tool.name}
              </span>

              {/* Tooltip Popup container */}
              <div className="absolute bottom-[108%] left-1/2 -translate-x-1/2 w-56 p-4 rounded-2xl liquid-glass border border-primary/25 shadow-xl opacity-0 translate-y-1 group-hover/tooltip:opacity-100 group-hover/tooltip:translate-y-0 transition-all duration-300 pointer-events-none z-50 text-center text-xs backdrop-blur-xl">
                <div className="font-mono text-[9px] text-primary font-extrabold uppercase tracking-wider mb-1">
                  {tool.exp}
                </div>
                <p className="text-on-surface text-[11px] leading-snug font-sans font-medium">
                  {tool.desc}
                </p>
                {/* Tooltip triangle indicator */}
                <div className="absolute top-full left-1/2 -translate-x-1/2 border-6 border-transparent border-t-white/80 dark:border-t-surface-container/80" />
              </div>
            </div>
          );
        })}
      </div>

      {/* Competencies and Certifications row */}
      <div className="mt-20 grid grid-cols-1 md:grid-cols-2 gap-16">
        {/* Core Competencies bar meters */}
        <div className="space-y-8">
          <h3 className="font-headline text-2xl font-bold mb-8">Core Competencies</h3>
          <div className="space-y-6">
            {competencies.map((comp, idx) => (
              <div key={idx} className="relative group/tooltip cursor-help">
                <div className="flex justify-between mb-2">
                  <span className="font-mono text-[11px] uppercase tracking-wider font-extrabold text-on-surface-variant">
                    {comp.name}
                  </span>
                  <span className="font-mono text-[11px] font-bold text-primary">
                    {comp.value}%
                  </span>
                </div>
                <div className="h-3.5 bg-outline-variant/20 rounded-full overflow-hidden backdrop-blur-md relative border border-outline-variant/15 shadow-inner">
                  <motion.div 
                    initial={{ width: 0 }}
                    whileInView={{ width: `${comp.value}%` }}
                    viewport={{ once: true, margin: "-20px" }}
                    transition={{ duration: 1.4, ease: [0.19, 1, 0.22, 1] }}
                    className="h-full bg-gradient-to-r from-primary/60 via-primary to-primary rounded-full relative shadow-[0_1px_4px_rgba(76,104,63,0.35),inset_0_1.5px_2px_rgba(255,255,255,0.4)] overflow-hidden"
                  >
                    {/* Animated glistening liquid reflection wave overlay */}
                    <motion.div 
                      animate={{ x: ['-100%', '200%'] }}
                      transition={{ repeat: Infinity, duration: 2.8, ease: "linear" }}
                      className="absolute inset-y-0 w-2/3 bg-gradient-to-r from-white/0 via-white/20 to-white/0 transform skew-x-12"
                    />
                    
                    {/* Pulsing droplet tip node */}
                    <div className="absolute right-1 top-1/2 -translate-y-1/2 w-1.5 h-1.5 rounded-full bg-white/90 shadow-md animate-pulse shrink-0" />
                  </motion.div>
                </div>

                {/* Tooltip container */}
                <div className="absolute bottom-[108%] left-4 lg:left-1/2 lg:-translate-x-1/2 w-64 p-4 rounded-2xl liquid-glass border border-primary/25 shadow-xl opacity-0 translate-y-1 group-hover/tooltip:opacity-100 group-hover/tooltip:translate-y-0 transition-all duration-300 pointer-events-none z-50 text-left text-xs backdrop-blur-xl">
                  <div className="font-mono text-[9px] text-primary font-extrabold uppercase tracking-wider mb-1">
                    Specialization Detail
                  </div>
                  <p className="text-on-surface text-[11px] leading-relaxed font-sans font-medium">
                    {comp.detail}
                  </p>
                  <div className="absolute top-full left-6 lg:left-1/2 lg:-translate-x-1/2 border-6 border-transparent border-t-white/80 dark:border-t-surface-container/80" />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Certifications Card */}
        <div className="liquid-glass-active p-10 rounded-3xl relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-6 opacity-5 group-hover:opacity-10 transition-opacity duration-350">
            <Award className="w-32 h-32 text-primary" strokeWidth={1} />
          </div>
          
          <h3 className="font-headline text-2xl font-bold mb-8 flex items-center gap-2">
            <span>Certifications</span>
          </h3>
          
          <div className="space-y-6">
            {certifications.map((cert, idx) => (
              <div key={idx} className="flex items-start gap-4">
                <CheckCircle className="w-5 h-5 text-primary mt-1 shrink-0" />
                <div>
                  <p className="font-headline text-lg font-bold text-on-surface leading-tight">
                    {cert.title}
                  </p>
                  <p className="font-mono text-[11px] text-on-surface-variant uppercase tracking-wider mt-1 font-extrabold">
                    {cert.subtitle}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
